// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhaleWire.Infrastructure.Persistence;

#nullable disable

namespace WhaleWire.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WhaleWireDbContext))]
    [Migration("20260116205710_MakeLastHashNullable")]
    partial class MakeLastHashNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhaleWire.Infrastructure.Persistence.Entities.AddressLease", b =>
                {
                    b.Property<string>("LeaseKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lease_key");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.HasKey("LeaseKey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_address_leases_expires_at");

                    b.ToTable("address_leases", (string)null);
                });

            modelBuilder.Entity("WhaleWire.Infrastructure.Persistence.Entities.BlockchainEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("address");

                    b.Property<DateTime>("BlockTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("block_time");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_id");

                    b.Property<long>("Lt")
                        .HasColumnType("bigint")
                        .HasColumnName("lt");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_events_event_id");

                    b.HasIndex("Chain", "Address", "Lt")
                        .HasDatabaseName("ix_events_chain_address_lt");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("WhaleWire.Infrastructure.Persistence.Entities.Checkpoint", b =>
                {
                    b.Property<string>("Chain")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("chain");

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("address");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("LastHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_hash");

                    b.Property<long>("LastLt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_lt");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Chain", "Address", "Provider");

                    b.ToTable("checkpoints", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
